name: Playwright Allure reporting

on:

  push:
    branches:
      - main
  # schedule:
  #   - cron: "* */4 * * *"

jobs:
  build:
    
    runs-on: ubuntu-latest

    timeout-minutes: 60
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    
    - uses: actions/upload-artifact@master
      with:
        name: allure-results
        path: allure-results
        retention-days: 20
        
    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history

    - name: Post the link to the report
      if: always()
      uses: Sibz/github-status-action@v1
      with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          description: 'Playwright report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}


